version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=copy_cat
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  api:
    build: .
    entrypoint: "./start.sh"
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    depends_on:
      - db
