"""empty message

Revision ID: c0fa88cee551
Revises: ab955fa82ccf
Create Date: 2021-06-11 10:26:55.808419

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c0fa88cee551'
down_revision = 'ab955fa82ccf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('texts', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.alter_column('texts', 'text_string',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('texts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('texts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('texts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('texts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('texts', 'text_string',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('texts', 'deleted_at')
    # ### end Alembic commands ###
